// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPetShop.Data;

#nullable disable

namespace WebPetShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebPetShop.Models.BaiDangNhanNuoi", b =>
                {
                    b.Property<int>("MaBaiDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiDang"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("MaThuCungNhanNuoi")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ duyệt");

                    b.HasKey("MaBaiDang")
                        .HasName("PK__BaiDangN__BF5D50C56E2D950B");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("MaThuCungNhanNuoi");

                    b.ToTable("BaiDangNhanNuoi", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.BaoCaoDoanhThu", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<decimal?>("LoiNhuan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NguoiLap")
                        .HasColumnType("int");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongChiPhi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TongDonHang")
                        .HasColumnType("int");

                    b.HasKey("MaBaoCao")
                        .HasName("PK__BaoCaoDo__25A9188C72F9778F");

                    b.HasIndex("NguoiLap");

                    b.ToTable("BaoCaoDoanhThu", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.ChiTietChamSoc", b =>
                {
                    b.Property<int>("MaCtcs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTCS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtcs"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaKyGui")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaCtcs")
                        .HasName("PK__ChiTietC__1E4E48C4744EFA0F");

                    b.HasIndex("MaKyGui");

                    b.ToTable("ChiTietChamSoc", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCtdh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtdh"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCtdh")
                        .HasName("PK__ChiTietD__1E4E40F0CB3D44C1");

                    b.HasIndex("MaDh");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaCtgh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtgh"));

                    b.Property<int>("MaGh")
                        .HasColumnType("int")
                        .HasColumnName("MaGH");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaCtgh")
                        .HasName("PK__ChiTietG__1E4FAF546172E42D");

                    b.HasIndex("MaGh");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietGioHang", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.DanhGium", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int?>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime?>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaDanhGia")
                        .HasName("PK__DanhGia__AA9515BF7A434DCF");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSp");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DanhMuc__B37508872BE94D27");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.DonHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDh"));

                    b.Property<int?>("MaKm")
                        .HasColumnType("int")
                        .HasColumnName("MaKM");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhi")
                        .HasColumnType("int");

                    b.Property<string>("MaVanDon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDonViGiao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ duyệt");

                    b.HasKey("MaDh")
                        .HasName("PK__DonHang__27258661FDAAA8B1");

                    b.HasIndex("MaKm");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaPhi");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.GioHang", b =>
                {
                    b.Property<int>("MaGh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGh"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaGh")
                        .HasName("PK__GioHang__2725AE8533881736");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<int>("MaKeToan")
                        .HasColumnType("int");

                    b.Property<int?>("MaKyGui")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E0FD89A372");

                    b.HasIndex("MaDh");

                    b.HasIndex("MaKeToan");

                    b.HasIndex("MaKyGui");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.KhoHang", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKho"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiGiaoDich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNcc")
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime?>("NgayThucHien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NguoiThucHien")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaKho")
                        .HasName("PK__KhoHang__3BDA9350B366DC9B");

                    b.HasIndex("MaNcc");

                    b.HasIndex("MaSp");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("KhoHang", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKm"));

                    b.Property<decimal?>("GiaTriToiDa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int?>("SoLanSuDungToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaKm")
                        .HasName("PK__KhuyenMa__2725CF159BBEBD14");

                    b.HasIndex(new[] { "MaCode" }, "UQ__KhuyenMa__152C7C5CE4736415")
                        .IsUnique();

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.KyGuiThuCung", b =>
                {
                    b.Property<int>("MaKyGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKyGui"));

                    b.Property<string>("GiongLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateOnly?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<decimal?>("PhiKyGui")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenThuCung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang ký gửi");

                    b.Property<int?>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("MaKyGui")
                        .HasName("PK__KyGuiThu__2B9FA9BEAFEA1E7D");

                    b.HasIndex("MaKh");

                    b.ToTable("KyGuiThuCung", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.LichLamViec", b =>
                {
                    b.Property<int>("MaLichLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichLam"));

                    b.Property<string>("CaLam")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayLam")
                        .HasColumnType("date");

                    b.HasKey("MaLichLam")
                        .HasName("PK__LichLamV__0A7F064A0FED0DE0");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LichLamViec", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.LichSuHeThong", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HanhDong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThucHien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaLichSu")
                        .HasName("PK__LichSuHe__C443222AA4C7E898");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichSuHeThong", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.Property<int>("MaLichSuDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLichSuDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSuDh"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NguoiThucHien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiMoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichSuDh")
                        .HasName("PK__LichSuTr__1EBCBDED00E7051A");

                    b.HasIndex("MaDh");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("LichSuTrangThaiDonHang", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D762FC376884");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NguoiDun__55F68FC092605992")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNcc"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc")
                        .HasName("PK__NhaCungC__3A185DEB15CA175D");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.PhiGiaoHang", b =>
                {
                    b.Property<int>("MaPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhi"));

                    b.Property<string>("DonViGiao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KhuVuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PhiCoDinh")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PhiTheoKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ThoiGianUocTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhi")
                        .HasName("PK__PhiGiaoH__3AE0AA6574C45B95");

                    b.ToTable("PhiGiaoHang", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C2B6FE3D9");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.ThanhToanTrucTuyen", b =>
                {
                    b.Property<int>("MaTttt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTTTT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTttt"));

                    b.Property<int>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTttt")
                        .HasName("PK__ThanhToa__44843A5D938BBDC7");

                    b.HasIndex("MaDh");

                    b.ToTable("ThanhToanTrucTuyen", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.ThuCungNhanNuoi", b =>
                {
                    b.Property<int>("MaNhanNuoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanNuoi"));

                    b.Property<int>("MaKyGui")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa có người nhận");

                    b.HasKey("MaNhanNuoi")
                        .HasName("PK__ThuCungN__A03CFC07E2869939");

                    b.HasIndex("MaKyGui");

                    b.ToTable("ThuCungNhanNuoi", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.YeuThich", b =>
                {
                    b.Property<int>("MaYt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaYT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYt"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime?>("NgayThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaYt")
                        .HasName("PK__YeuThich__272330D4E7581D41");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSp");

                    b.ToTable("YeuThich", (string)null);
                });

            modelBuilder.Entity("WebPetShop.Models.BaiDangNhanNuoi", b =>
                {
                    b.HasOne("WebPetShop.Models.NguoiDung", "MaNguoiTaoNavigation")
                        .WithMany("BaiDangNhanNuois")
                        .HasForeignKey("MaNguoiTao")
                        .IsRequired()
                        .HasConstraintName("FK__BaiDangNh__MaNgu__2BFE89A6");

                    b.HasOne("WebPetShop.Models.ThuCungNhanNuoi", "MaThuCungNhanNuoiNavigation")
                        .WithMany("BaiDangNhanNuois")
                        .HasForeignKey("MaThuCungNhanNuoi")
                        .IsRequired()
                        .HasConstraintName("FK__BaiDangNh__MaThu__2B0A656D");

                    b.Navigation("MaNguoiTaoNavigation");

                    b.Navigation("MaThuCungNhanNuoiNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.BaoCaoDoanhThu", b =>
                {
                    b.HasOne("WebPetShop.Models.NguoiDung", "NguoiLapNavigation")
                        .WithMany("BaoCaoDoanhThus")
                        .HasForeignKey("NguoiLap")
                        .HasConstraintName("FK__BaoCaoDoa__Nguoi__245D67DE");

                    b.Navigation("NguoiLapNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.ChiTietChamSoc", b =>
                {
                    b.HasOne("WebPetShop.Models.KyGuiThuCung", "MaKyGuiNavigation")
                        .WithMany("ChiTietChamSocs")
                        .HasForeignKey("MaKyGui")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietCh__MaKyG__71D1E811");

                    b.Navigation("MaKyGuiNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("WebPetShop.Models.DonHang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaDH__60A75C0F");

                    b.HasOne("WebPetShop.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaSP__619B8048");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("WebPetShop.Models.GioHang", "MaGhNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGio__MaGH__5812160E");

                    b.HasOne("WebPetShop.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGio__MaSP__59063A47");

                    b.Navigation("MaGhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.DanhGium", b =>
                {
                    b.HasOne("WebPetShop.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__DanhGia__MaNguoi__0F624AF8");

                    b.HasOne("WebPetShop.Models.SanPham", "MaSpNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK__DanhGia__MaSP__10566F31");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.DonHang", b =>
                {
                    b.HasOne("WebPetShop.Models.KhuyenMai", "MaKmNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKm")
                        .HasConstraintName("FK__DonHang__MaKM__02FC7413");

                    b.HasOne("WebPetShop.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__DonHang__MaNguoi__5DCAEF64");

                    b.HasOne("WebPetShop.Models.PhiGiaoHang", "MaPhiNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaPhi")
                        .HasConstraintName("FK__DonHang__MaPhi__06CD04F7");

                    b.Navigation("MaKmNavigation");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaPhiNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.GioHang", b =>
                {
                    b.HasOne("WebPetShop.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__GioHang__MaNguoi__5441852A");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.HoaDon", b =>
                {
                    b.HasOne("WebPetShop.Models.DonHang", "MaDhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaDh")
                        .HasConstraintName("FK__HoaDon__MaDH__7B5B524B");

                    b.HasOne("WebPetShop.Models.NguoiDung", "MaKeToanNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKeToan")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__MaKeToan__7A672E12");

                    b.HasOne("WebPetShop.Models.KyGuiThuCung", "MaKyGuiNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKyGui")
                        .HasConstraintName("FK__HoaDon__MaKyGui__7C4F7684");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaKeToanNavigation");

                    b.Navigation("MaKyGuiNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.KhoHang", b =>
                {
                    b.HasOne("WebPetShop.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("KhoHangs")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK__KhoHang__MaNCC__68487DD7");

                    b.HasOne("WebPetShop.Models.SanPham", "MaSpNavigation")
                        .WithMany("KhoHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__KhoHang__MaSP__6754599E");

                    b.HasOne("WebPetShop.Models.NguoiDung", "NguoiThucHienNavigation")
                        .WithMany("KhoHangs")
                        .HasForeignKey("NguoiThucHien")
                        .IsRequired()
                        .HasConstraintName("FK__KhoHang__NguoiTh__693CA210");

                    b.Navigation("MaNccNavigation");

                    b.Navigation("MaSpNavigation");

                    b.Navigation("NguoiThucHienNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.KyGuiThuCung", b =>
                {
                    b.HasOne("WebPetShop.Models.NguoiDung", "MaKhNavigation")
                        .WithMany("KyGuiThuCungs")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__KyGuiThuCu__MaKH__6E01572D");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.LichLamViec", b =>
                {
                    b.HasOne("WebPetShop.Models.NguoiDung", "MaNhanVienNavigation")
                        .WithMany("LichLamViecs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__LichLamVi__MaNha__17F790F9");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.LichSuHeThong", b =>
                {
                    b.HasOne("WebPetShop.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("LichSuHeThongs")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuHeT__MaNgu__1BC821DD");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.HasOne("WebPetShop.Models.DonHang", "MaDhNavigation")
                        .WithMany("LichSuTrangThaiDonHangs")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuTran__MaDH__1F98B2C1");

                    b.HasOne("WebPetShop.Models.NguoiDung", "NguoiThucHienNavigation")
                        .WithMany("LichSuTrangThaiDonHangs")
                        .HasForeignKey("NguoiThucHien")
                        .HasConstraintName("FK__LichSuTra__Nguoi__208CD6FA");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("NguoiThucHienNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.SanPham", b =>
                {
                    b.HasOne("WebPetShop.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__MaDanhM__5070F446");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.ThanhToanTrucTuyen", b =>
                {
                    b.HasOne("WebPetShop.Models.DonHang", "MaDhNavigation")
                        .WithMany("ThanhToanTrucTuyens")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__ThanhToanT__MaDH__0A9D95DB");

                    b.Navigation("MaDhNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.ThuCungNhanNuoi", b =>
                {
                    b.HasOne("WebPetShop.Models.KyGuiThuCung", "MaKyGuiNavigation")
                        .WithMany("ThuCungNhanNuois")
                        .HasForeignKey("MaKyGui")
                        .IsRequired()
                        .HasConstraintName("FK__ThuCungNh__MaKyG__76969D2E");

                    b.Navigation("MaKyGuiNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.YeuThich", b =>
                {
                    b.HasOne("WebPetShop.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__YeuThich__MaNguo__14270015");

                    b.HasOne("WebPetShop.Models.SanPham", "MaSpNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__YeuThich__MaSP__151B244E");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebPetShop.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebPetShop.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("HoaDons");

                    b.Navigation("LichSuTrangThaiDonHangs");

                    b.Navigation("ThanhToanTrucTuyens");
                });

            modelBuilder.Entity("WebPetShop.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("WebPetShop.Models.KhuyenMai", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebPetShop.Models.KyGuiThuCung", b =>
                {
                    b.Navigation("ChiTietChamSocs");

                    b.Navigation("HoaDons");

                    b.Navigation("ThuCungNhanNuois");
                });

            modelBuilder.Entity("WebPetShop.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiDangNhanNuois");

                    b.Navigation("BaoCaoDoanhThus");

                    b.Navigation("DanhGia");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");

                    b.Navigation("KhoHangs");

                    b.Navigation("KyGuiThuCungs");

                    b.Navigation("LichLamViecs");

                    b.Navigation("LichSuHeThongs");

                    b.Navigation("LichSuTrangThaiDonHangs");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("WebPetShop.Models.NhaCungCap", b =>
                {
                    b.Navigation("KhoHangs");
                });

            modelBuilder.Entity("WebPetShop.Models.PhiGiaoHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebPetShop.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("DanhGia");

                    b.Navigation("KhoHangs");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("WebPetShop.Models.ThuCungNhanNuoi", b =>
                {
                    b.Navigation("BaiDangNhanNuois");
                });
#pragma warning restore 612, 618
        }
    }
}
